//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bebida> Bebidas { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Ensalada> Ensaladas { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Plato> Platos { get; set; }
        public virtual DbSet<Postre> Postres { get; set; }
        public virtual DbSet<Restaurante> Restaurantes { get; set; }
        public virtual DbSet<Ubicacione> Ubicaciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int InsertarBebida(Nullable<int> id_Bebidas, string descripcion_Bebidas)
        {
            var id_BebidasParameter = id_Bebidas.HasValue ?
                new ObjectParameter("Id_Bebidas", id_Bebidas) :
                new ObjectParameter("Id_Bebidas", typeof(int));
    
            var descripcion_BebidasParameter = descripcion_Bebidas != null ?
                new ObjectParameter("Descripcion_Bebidas", descripcion_Bebidas) :
                new ObjectParameter("Descripcion_Bebidas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarBebida", id_BebidasParameter, descripcion_BebidasParameter);
        }
    
        public virtual int InsertarCategorias(Nullable<int> id_Categoria, string descripcion_categoria)
        {
            var id_CategoriaParameter = id_Categoria.HasValue ?
                new ObjectParameter("Id_Categoria", id_Categoria) :
                new ObjectParameter("Id_Categoria", typeof(int));
    
            var descripcion_categoriaParameter = descripcion_categoria != null ?
                new ObjectParameter("Descripcion_categoria", descripcion_categoria) :
                new ObjectParameter("Descripcion_categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarCategorias", id_CategoriaParameter, descripcion_categoriaParameter);
        }
    
        public virtual int InsertarEnsaladas(Nullable<int> id_Ensaladas, string descripcion_Ensaladas)
        {
            var id_EnsaladasParameter = id_Ensaladas.HasValue ?
                new ObjectParameter("Id_Ensaladas", id_Ensaladas) :
                new ObjectParameter("Id_Ensaladas", typeof(int));
    
            var descripcion_EnsaladasParameter = descripcion_Ensaladas != null ?
                new ObjectParameter("Descripcion_Ensaladas", descripcion_Ensaladas) :
                new ObjectParameter("Descripcion_Ensaladas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarEnsaladas", id_EnsaladasParameter, descripcion_EnsaladasParameter);
        }
    
        public virtual int InsertarMenus(Nullable<int> id_Menu, Nullable<int> id_Categorias, Nullable<int> id_Plato)
        {
            var id_MenuParameter = id_Menu.HasValue ?
                new ObjectParameter("Id_Menu", id_Menu) :
                new ObjectParameter("Id_Menu", typeof(int));
    
            var id_CategoriasParameter = id_Categorias.HasValue ?
                new ObjectParameter("Id_Categorias", id_Categorias) :
                new ObjectParameter("Id_Categorias", typeof(int));
    
            var id_PlatoParameter = id_Plato.HasValue ?
                new ObjectParameter("Id_Plato", id_Plato) :
                new ObjectParameter("Id_Plato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarMenus", id_MenuParameter, id_CategoriasParameter, id_PlatoParameter);
        }
    
        public virtual int InsertarPlatos(Nullable<int> id_Plato, Nullable<int> id_Menu, string descripción_Plato, Nullable<int> id_postres, Nullable<int> id_Ensaladas, Nullable<int> id_Bebidas, Nullable<bool> combo_Plato, Nullable<bool> promocion_Plato, Nullable<decimal> valor_Plato, string imagen)
        {
            var id_PlatoParameter = id_Plato.HasValue ?
                new ObjectParameter("Id_Plato", id_Plato) :
                new ObjectParameter("Id_Plato", typeof(int));
    
            var id_MenuParameter = id_Menu.HasValue ?
                new ObjectParameter("Id_Menu", id_Menu) :
                new ObjectParameter("Id_Menu", typeof(int));
    
            var descripción_PlatoParameter = descripción_Plato != null ?
                new ObjectParameter("Descripción_Plato", descripción_Plato) :
                new ObjectParameter("Descripción_Plato", typeof(string));
    
            var id_postresParameter = id_postres.HasValue ?
                new ObjectParameter("Id_postres", id_postres) :
                new ObjectParameter("Id_postres", typeof(int));
    
            var id_EnsaladasParameter = id_Ensaladas.HasValue ?
                new ObjectParameter("Id_Ensaladas", id_Ensaladas) :
                new ObjectParameter("Id_Ensaladas", typeof(int));
    
            var id_BebidasParameter = id_Bebidas.HasValue ?
                new ObjectParameter("Id_Bebidas", id_Bebidas) :
                new ObjectParameter("Id_Bebidas", typeof(int));
    
            var combo_PlatoParameter = combo_Plato.HasValue ?
                new ObjectParameter("Combo_Plato", combo_Plato) :
                new ObjectParameter("Combo_Plato", typeof(bool));
    
            var promocion_PlatoParameter = promocion_Plato.HasValue ?
                new ObjectParameter("Promocion_Plato", promocion_Plato) :
                new ObjectParameter("Promocion_Plato", typeof(bool));
    
            var valor_PlatoParameter = valor_Plato.HasValue ?
                new ObjectParameter("Valor_Plato", valor_Plato) :
                new ObjectParameter("Valor_Plato", typeof(decimal));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarPlatos", id_PlatoParameter, id_MenuParameter, descripción_PlatoParameter, id_postresParameter, id_EnsaladasParameter, id_BebidasParameter, combo_PlatoParameter, promocion_PlatoParameter, valor_PlatoParameter, imagenParameter);
        }
    
        public virtual int InsertarPostres(Nullable<int> id_postres, string descripcion_postres)
        {
            var id_postresParameter = id_postres.HasValue ?
                new ObjectParameter("Id_postres", id_postres) :
                new ObjectParameter("Id_postres", typeof(int));
    
            var descripcion_postresParameter = descripcion_postres != null ?
                new ObjectParameter("Descripcion_postres", descripcion_postres) :
                new ObjectParameter("Descripcion_postres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarPostres", id_postresParameter, descripcion_postresParameter);
        }
    
        public virtual int InsertarRestaurantes(Nullable<int> id_restaurante, string nombre, Nullable<int> id_Categorias, Nullable<int> id_Menu)
        {
            var id_restauranteParameter = id_restaurante.HasValue ?
                new ObjectParameter("Id_restaurante", id_restaurante) :
                new ObjectParameter("Id_restaurante", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var id_CategoriasParameter = id_Categorias.HasValue ?
                new ObjectParameter("Id_Categorias", id_Categorias) :
                new ObjectParameter("Id_Categorias", typeof(int));
    
            var id_MenuParameter = id_Menu.HasValue ?
                new ObjectParameter("Id_Menu", id_Menu) :
                new ObjectParameter("Id_Menu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarRestaurantes", id_restauranteParameter, nombreParameter, id_CategoriasParameter, id_MenuParameter);
        }
    
        public virtual int InsertarUbicaciones(Nullable<int> id_Ubicación, string descripcion, Nullable<int> id_Restaurante, Nullable<int> telefono1, Nullable<int> telefono2, string correo)
        {
            var id_UbicaciónParameter = id_Ubicación.HasValue ?
                new ObjectParameter("Id_Ubicación", id_Ubicación) :
                new ObjectParameter("Id_Ubicación", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var id_RestauranteParameter = id_Restaurante.HasValue ?
                new ObjectParameter("Id_Restaurante", id_Restaurante) :
                new ObjectParameter("Id_Restaurante", typeof(int));
    
            var telefono1Parameter = telefono1.HasValue ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(int));
    
            var telefono2Parameter = telefono2.HasValue ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarUbicaciones", id_UbicaciónParameter, descripcionParameter, id_RestauranteParameter, telefono1Parameter, telefono2Parameter, correoParameter);
        }
    }
}
