//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plato()
        {
            this.Menus = new HashSet<Menu>();
        }
    
        public int Id_Plato { get; set; }
        public int Id_Menu { get; set; }
        public string Descripcion_Plato { get; set; }
        public Nullable<int> Id_Postres { get; set; }
        public Nullable<int> Id_Ensaladas { get; set; }
        public Nullable<int> Id_Bebidas { get; set; }
        public Nullable<bool> Combo_Plato { get; set; }
        public Nullable<bool> Promocion_Plato { get; set; }
        public decimal Valor_Plato { get; set; }
        public string Imagen { get; set; }
    
        public virtual Bebida Bebida { get; set; }
        public virtual Ensalada Ensalada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Postre Postre { get; set; }
    }
}
